using System;
using System.Collections.Generic;
using System.Linq;

namespace statsCollector.Domain;

public sealed record PlayerSnapshot
(
    int? MatchId,
    string? MatchUuid,
    int RoundNumber,
    DateTime RoundStartUtc,
    int AliveOnTeamAtRoundStart,
    int AliveEnemyAtRoundStart,

    ulong SteamId,
    string Name,
    int Kills,
    int Deaths,
    int Assists,
    int Headshots,
    int DamageDealt,
    int DamageTaken,
    int DamageArmor,
    int ShotsFired,
    int ShotsHit,
    int Mvps,
    int Score,
    int RoundsPlayed,
    int RoundsWon,
    
    int CtRounds,
    int TRounds,
    
    int BombPlants,
    int BombDefuses,
    int BombPlantAttempts,
    int BombPlantAborts,
    int BombDefuseAttempts,
    int BombDefuseAborts,
    int BombDefuseWithKit,
    int BombDefuseWithoutKit,
    int BombDrops,
    int BombPickups,
    int DefuserDrops,
    int DefuserPickups,
    int ClutchDefuses,
    int TotalPlantTime,
    int TotalDefuseTime,
    
    int HostagesRescued,
    
    int GrenadesThrown,
    int FlashesThrown,
    int SmokesThrown,
    int MolotovsThrown,
    int HeGrenadesThrown,
    int DecoysThrown,
    int TacticalGrenadesThrown,
    int PlayersBlinded,
    int TimesBlinded,
    int FlashAssists,
    float TotalBlindTime,
    float TotalBlindTimeInflicted,
    int UtilityDamageDealt,
    int UtilityDamageTaken,
    int BombKills,
    int BombDeaths,
    
    int Jumps,
    int TotalSpawns,
    int PlaytimeSeconds,
    
    int MoneySpent,
    int EquipmentValue,
    int ItemsPurchased,
    int ItemsPickedUp,
    int ItemsDropped,
    int CashEarned,
    int CashSpent,
    int LossBonus,
    int RoundStartMoney,
    int RoundEndMoney,
    int EquipmentValueStart,
    int EquipmentValueEnd,
    
    int EnemiesFlashed,
    int TeammatesFlashed,
    int EffectiveFlashes,
    int EffectiveSmokes,
    int EffectiveHEGrenades,
    int EffectiveMolotovs,
    int MultiKillNades,
    int NadeKills,
    int TradeWindowsMissed,
    int FlashWaste,
    int EntryKills,
    int EntryDeaths,
    int EntryKillAttempts,
    int EntryKillAttemptWins,
    int TradeKills,
    int TradedDeaths,
    int HighImpactKills,
    int LowImpactKills,
    int TradeOpportunities,
    int MultiKills,
    int OpeningDuelsWon,
    int OpeningDuelsLost,
    int NoscopeKills,
    int ThruSmokeKills,
    int AttackerBlindKills,
    int FlashAssistedKills,
    int WallbangKills,
    int Revenges,
    int ClutchesWon,
    int ClutchesLost,
    decimal ClutchPoints,
    int MvpsEliminations,
    int MvpsBomb,
    int MvpsHostage,
    
    int HeadshotsHit,
    int ChestHits,
    int StomachHits,
    int ArmHits,
    int LegHits,
    
    int CurrentRoundKills,
    int CurrentRoundDeaths,
    int CurrentRoundShotsFired,
    bool HadKillThisRound,
    bool HadAssistThisRound,
    bool SurvivedThisRound,
    bool WasTradedThisRound,
    bool DidTradeThisRound,
    bool WasFlashedForKill,
    int KASTRounds,
    int Pings,
    int Footsteps,

    decimal WeightedKills,
    int TeamFlashDuration,
    int FlashAssistDuration,
    int WastedFlashes,

    IReadOnlyDictionary<string, int> WeaponKills,
    IReadOnlyDictionary<string, int> WeaponShots,
    IReadOnlyDictionary<string, int> WeaponHits,

    // Calculated metrics added to snapshot for persistence
    decimal KDRatio,
    decimal HeadshotPercentage,
    decimal AccuracyPercentage,
    decimal KASTPercentage,
    decimal AverageDamagePerRound,
    decimal HLTVRating,
    decimal ImpactRating,
    decimal UtilityScore,
    decimal PerformanceScore,
    string PlayerRank,
    decimal AverageKillsPerRound,
    decimal AverageDeathsPerRound,
    decimal AverageAssistsPerRound,
    decimal ClutchSuccessRate,
    decimal TradeKillRatio,
    decimal OpeningKillRatio,
    decimal GrenadeEffectivenessRate,
    decimal FlashEffectivenessRate,
    decimal UtilityUsagePerRound,
    decimal AverageMoneySpentPerRound,
    decimal SurvivalRating,
    decimal UtilityImpactScore,
    string TopWeaponByKills
);
